use_server_listing_service: 'false'

server_address: "xxx.x.x.x"

server_name: 'CivilizationCraft'

server_timezone: 'CST'

server_description: 'Just Minecraftonly server'

server_url: 'minecraftonly.ru'
server_url_description: 'CivCraft Minecraftonly'

debug_heartbeat: 'false'

localization_file: "default_lang.yml"

mysql:
   hostname: xxx
   port: 'xxxx'
   database: xxx
   username: xxx
   password: 'xxx
   table_prefix: 'xxx'
   min_conns: '5'
   max_conns: '10'
   parts: 'xxx'
   
global_database:
    database: global
    hostname: xxx
    port: 'xxx'
    username: xxx
    password: 'xxx'
    min_conns: 'xxx'
    max_conns: 'xxx'
    parts: 'xxx'

server_phase: 'xxx'

 
