name: CivCraft
main: com.avrgaming.civcraft.main.CivCraft
softdepends: [TitleAPI]
version: 1.76.5

commands:
    town:
        aliases: [t] [е]
    plot:
        aliases: [p] [з]
    resident:
        aliases: [res] [кус] 
    dbg:
        aliases:
    accept:
        aliases: [yes] [y] [нуы]
    deny:
        aliases: [no] [n] [тщ]
    civ:
        aliases: [c] [с]
    tc:
        aliases: [ес]
    cc:
        aliases: [сс]
    ac:
        aliases:
    gc:
        aliases:
    ad:
        aliases:
    build:
        aliases:
    market:
        aliases: [m]
    select:
        aliases:
    econ:
        aliases: [money] [ьщтун]
    pay:
        aliases:
    here:
        aliases:
    camp:
        aliases:
    report:
        aliases:
    kill:
        aliases:
    team:
        aliases:
    sb:
        aliases:
